### ISSUE TITLE
How to obtain IFR Clearance at Preparing the MCDU activity

### ISSUE THREAD

**Issue by pjakrishnan** [flybywiresim/docs#369]
Hello,

The A32NX dcument has the following prerequisites at the Preparing the MCDU activity.
Below are a few Prerequisites before programming the MCDU.

Visit Starting the Aircraft to learn more.

Make sure the aircraft is powered up.
External Power OR APU
Make sure the ADIRS are set to NAV.
Have a valid flight plan.
Ensure IFR clearance has been obtained.

The last one says to ensure IFR clearance is obtained.
If using the built-in ATC, how can we do this before entering a Flight Plan.

Where am I missing the point?
Thanks
Ananth

**Comment by frankkopp** [comment]
> Hello,
> 
> 
> 
> The A32NX dcument has the following prerequisites at the Preparing the MCDU activity.
> 
> Below are a few Prerequisites before programming the MCDU.
> 
> 
> 
> Visit Starting the Aircraft to learn more.
> 
> 
> 
> Make sure the aircraft is powered up.
> 
> External Power OR APU
> 
> Make sure the ADIRS are set to NAV.
> 
> Have a valid flight plan.
> 
> Ensure IFR clearance has been obtained.
> 
> 
> 
> The last one says to ensure IFR clearance is obtained.
> 
> If using the built-in ATC, how can we do this before entering a Flight Plan.
> 
> 
> 
> Where am I missing the point?
> 
> Thanks
> 
> Ananth

Hi Ananth,

The beginner guide has real or Online ATC procedures in mind and not the MSFS internal ATC. MSFS's ATC is unfortunately very bad, buggy and unrealistic. And the last is very relevant for the guide. We do not want to teach wrong procedures to pilots just because the MSFS ATC is so bad. 

We do comment at some places in the guide on MSFS's differences. But we do not do this every time ATC is mentioned.

Example:
![image](https://user-images.githubusercontent.com/16833201/147341951-5ac0b5f1-b994-472b-a075-f9c99775e7fd.jpeg)

We should maybe point it out more clearly that the guide does not have MSFS's ATC in mind but real or online ATC procedures. 

If you want to use the MSFS ATC you still can but you might need to be flexible in the places the guide mentions ATC. 

Thanks + Cheers
Mav

PS: Please close the issue after reading.

**Comment by pjakrishnan** [comment]
Thanks for clarifying.

I have still to grow to try online ATC so stuck with builtin.

I shall bend the procedure to go for IFR clearance after creating the Flight Plan in MCDU I think that should be possible.
