### ISSUE TITLE
Approach Guide: Conflicting Flaps recommendation

### ISSUE THREAD

**Issue by MSVF** [flybywiresim/docs#378]
Hi,

in the [Approach and ILS Landing guide](https://docs.flybywiresim.com/pilots-corner/beginner-guide/landing/), there are conflicting flaps recommendations. Or maybe I'm reading them wrong, I'm still learning, hence I might be a good dummy for the beginners guide.

1. Chapter "Intercepting the ILS localizer", quote: "Set FLAPS to 1 at about VFE -15 knots (but never before speed is below VFE) for the first slat/flap configuration (CONF1). The aircraft will then decelerate further to prepare for the next flaps configuration. **Our target is to be CONF 1 at S speed by the time you get to the glideslope intercept.**"
2. Chapter "Intercepting the ILS Glideslope", quote: "There is different guidance when to set FLAPS 2 but for beginners **we recommend to go to FLAPS 2 before starting the glideslope descent.**"

The first chapter talks about the point arriving at the GS, the second chapter about before starting the GS. So for me that sounds like the same point-in-time, but with two different flaps recommendation: 1 or 2. Let me know what you think.

Best

MSVF

**Comment by frankkopp** [comment]
I don't think it is contradicting but maybe not as clear as it could be. 

Our target is to be CONF 1 at S speed by the time you get to the glideslope intercept. 
=> this actually allows to set CONFIG 2 (because of the speed) so it must happen before the GS intercept and before CONFIG 2.

The reason we recommend this "...to go to FLAPS 2 before starting the glideslope descent." for beginners is that beginners tend to have issues slowing down the aircraft (esp. the A320NEO) as they usually are too fast when starting the G/S descent. CONFIG 2 will help with slowing down and increasing drag and if done before descending allows the aircraft to slow down enough so the descent does not make it faster again.

I'll think of a way to make this clearer. Might be as simple as adding 
"Our target is to be CONF 1 at S speed by the time you need to set CONFIG 2 for the glideslope intercept."

WDYT?

**Comment by MSVF** [comment]
Thanks for your swift reply.

To be honest, I head to read your addition 2-3 times, but I think it's clearer now! You might even add your sentence about _"this actually allows to set CONFIG 2 (because of the speed) so it must happen before the GS intercept and before CONFIG 2."_.

**Comment by frankkopp** [comment]
Made another update. Thanks for the feedback. Will close this now.

**Comment by MSVF** [comment]
Thanks! In terms of polishing, you might want to fix an typo (marked in bold) of the update:
"Our target is to be in CONF 1 and at S-speed by the time you need to set flaps 2 (CONFIG 2) before the glideslope intercept **as** S-speed will be slow enough to set flaps 2 (CONFIG 2)."
