### ISSUE TITLE
Instruct how to make built-in ATC give IFR options

### ISSUE THREAD

**Issue by sensibleish** [flybywiresim/docs#387]
I suggest a small addition to the beginner guide Preflight section so pilots know how to make the built-in ATC give IFR options.

The Preflight page's _Flight Planning_ section says:

> We highly recommend **not** using the built-in MSFS flight planner (World Map).

From what I can tell, if you want built-in ATC to offer choices relevant to IFR, you must use the World Map a little! You must select departure and arrival airports and set the flight mode to `IFR`.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1753270/147887178-a06aedcf-bcb4-418c-bfa1-804114939578.png">

Without this, built-in ATC behaves totally differently (VFR options only?). You cannot correctly perform many steps from later in the guide.

Can someone confirm that my understanding is correct? If so, I'd be happy to work on a small PR for review.

**Comment by frankkopp** [comment]
Thanks for your feedback, much appreciated!

We actually deliberately do not want users to use the World Map or MSFS ATC. The whole beginner guide is done with Online ATC or even real ATC in mind. 

MSFS ATC is rather bad, unrealistic and buggy and we do not recommend to use it at all.
It "teaches" new pilots unrealistic things and confuses even more experienced users because of the many issues and bugs it presents. 

In addition to that, not using the World Map is a requirement to be able to use the simBrief integration. You can only use the INIT* on the INIT A page when no destination is chosen in the World Map. 

We might change this at some point in time but we would require the in-game ATC to be much more realistic and stable than it is today.

**Comment by sensibleish** [comment]
Makes sense! Perhaps a stronger note about this would be good for the Preflight page. Thank you!
