### ISSUE TITLE
Changes to limitations

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/docs#648]
I have a few comments on the limitations section: 
1) Where did you get 3% for the runway slope limitation? It's 2% in the AFM in our docs folder; 
2) Conf 1 and 1+f have different limiting airspeeds. 1+f is 215 KCAS and Conf 2 is 200; 
3) OEW is not a limitation; 
4) How about adding the icing limitations?; 
5) VLO in the AFM we have it does not show a Mach limitation, it's only in terms of KCAS; 
6) Why show VCMA and VMCG up to 15100 ft when you are using the 9200 ft limit for takeoff and landing ; and 
7) Minor editorial quibble - I suggest one engine inoperative (singular) rather than one engines inoperative in the engine limitations.

**Comment by donstim** [comment]
The 3% for the runway slope limitation may have just been a typo. The FCOM also shows it as +-2%.

Regarding the environmental envelope, I see the FCOM is based on having the 14,100 foot altitude capability mod, even for the NEO. The environmental envelope we are using for the airplane is based on the basic capability, as reflected in the Airplane Flight Manual (9,200 ft max takeoff and landing altitude). That's why the VMCA and VMCG tables in the FCOM don't stop at 9200 feet. I wouldn't fret over that; go ahead and keep what you have. Or, maybe we should consider opening up the environmental envelope of the A32NX.

Also, I see where you got your VLOs. I don't know why the AFM quotes them one way and the FCOM another. You can disregard that comment as well.

Here is the AFM page for the icing limitations, which might be nice to have to use for people asking questions about when to turn engine anti-ice on):
![Screenshot (2251)](https://user-images.githubusercontent.com/70166617/191378894-839b156f-7245-4321-91a6-9ee9d15aa63b.png)

**Comment by frankkopp** [comment]
@donstim https://github.com/flybywiresim/docs/pull/654
The 2% was indeed a typo or I took it from the wrong table. 
Added the Icing info - btw. there will be a separate page on icing:
https://github.com/flybywiresim/docs/pull/652
