### ISSUE TITLE
Add extra info about windows 11 terminal for simbridge 

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#679]
Reference: Fender in #docs

Please add the information into this issue below so I can get it sorted :).

**Comment by absprouse23** [comment]
With the Windows 11 22H2 update, Windows Terminal is now the default terminal on Windows 11. Because Windows Terminal no longer supports being minimized to the tray, this feature no longer works on Windows 11.

Steps to regain functionality:
1. Open settings, and navigate to `Privacy & Security --> For Developers`
![image](https://user-images.githubusercontent.com/115891926/202870317-0788420e-88fa-4d57-a35a-aac42e5c67d0.png)
2. Set Terminal to `Windows Console Host`
![image](https://user-images.githubusercontent.com/115891926/202870338-ab17229c-4118-4ce3-8919-e22b558f3a45.png)
3. Close the settings app and open Simbridge, it should now open in the legacy Windows Console Host.
![image](https://user-images.githubusercontent.com/115891926/202870394-420cd796-b695-44e0-a51a-3728f4479c3a.png)

Simbridge should now be able to be minimized to the tray properly.
